### ISSUE TITLE
Throttle based on graphql params instead of context

### ISSUE THREAD

**Issue by grinono** [nestjs/throttler#1190]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We would like to throttle based on params the user sends in the request. So instead of the context. For some mutations we would like to limit based on input value: accountId the number of request that can be send per 10 seconds. 

### Describe the solution you'd like

Adding a decorator where we can set the field that should be unique per request within the time limit. @FieldThrottle("account", 1, 10)

### What is the motivation / use case for changing the behavior?

security

**Comment by jmcdo29** [comment]
You could extend the `ThrottlerGuard` and overwrite the [`getTracker` method](https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts#L96). Or even the [`generateKey`](https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts#L112) method so you have access to the `context` and call to `this.reflector.get()` and use `context.getHandler()` to get the current method's metadata. The `generateKey` usually returns an `md5` hash of `ClassName-MethodName-Ip` but you could make that whatever you want to and then you've got limiting based on a new key rather than IP

**Comment by grinono** [comment]
thanks it works
