### ISSUE TITLE
throttler will add more times in a request

### ISSUE THREAD

**Issue by fidelyiu** [nestjs/throttler#1365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

First I registered a Guard `{ttl: 10,limit: 20}` globally, then I wanted to override the Throttler configuration on a route, so I added another Guard to the route with `@Throttle(1, 60)`.

I thought this would limit the route to only one access a minute. But when I access the interface, the data stored in the store is `2`. This `2` exceeds the Throttler configuration on the route, so I never get the requested content.

### Minimum reproduction code

-

### Expected behavior

I expect that the `@Throttle` configuration on the route and the Guard configuration of the global Throttler will not be added repeatedly.

### Package version

4.0.0

### NestJS version

9.0.0

### Node.js version

16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by fidelyiu** [comment]
![image](https://user-images.githubusercontent.com/42163284/219851571-8f60c54a-2421-4e70-9448-a3ac1dadc04d.png)

You can also see in the debug that the request was added twice.

`handleRequest` >> `this.storageService.increment` >> `this.storage[key].totalHits++`

**Comment by fidelyiu** [comment]
https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts#L80

Before `this.storageService.increment` is executed, can we determine if the current request has already been processed by the throttler

**Comment by jmcdo29** [comment]
@kkoomen can you take a look at this? I think it's related to your recent changes

**Comment by jmcdo29** [comment]
Also, @fidelyiu can you provide a minimum reproduction to help us debug this?

**Comment by kkoomen** [comment]
@jmcdo29 @fidelyiu this is expected behavior, there is no bug here. In the end, this makes sense and has been implemented on purpose mainly for non-local storage providers, such as the redis one where there might be a request that isn't finished yet, meanwhile another request got fired. In the end, you will receive in the guard the `totalHits` being done that will expire once `timeToExpire` reaches 0. As described in the README [here](https://github.com/nestjs/throttler#working-with-websockets) you should throw an error if the totalHits is strictly larger than the `limit` parameter.

**Comment by fidelyiu** [comment]
@kkoomen @jmcdo29 Okay, thanks a lot!
