### ISSUE TITLE
Adding documentation for IP behind a reverse proxy

### ISSUE THREAD

**Issue by leonardfactory** [nestjs/throttler#427]
Hi everybody! I've found this module pretty interesting, however digging in the source code I've found you're using `req.ip` which obviously is perfectly fine. 
However, in order to prevent issues for users trying the package, I think a tip in the README warning about the usage behind a reverse proxy could be extremely useful.

Since Express [requires the `trust proxy` option](http://expressjs.com/en/guide/behind-proxies.html) to be set to `true` in order to use the `X-Forwarded-For` client IP, and since Nginx should be configured accordingly, i.e. `proxy_set_header X-Forwarded-For $remote_addr;` ,  atleast a warning could be useful.

Am I missing something? Is this something that should be addressed atleast at a documentation level?
I'm leaving this note here just to be propositive and help someone, let me know what do you think about 😄

**Comment by jmcdo29** [comment]
Adding documentation would be great, definitely something we should mention. Also, we can probably [abstract this line out](https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts#L80) (or at least the `req.ip` part of it) to make it overridable so that people can track by different properties and create different keys if they want. It would also make it easier to swap to using a header instead of `req.ip` if that's preferred. Feel free to open a PR in the [docs repo](https://github.com/nestjs/docs.nestjs.com) to update the documentation (you can also update the README, but I'm more worried about it being right in the docs site). I'll work on getting the guard updated to have the ability to override the `req` property 😄

**Comment by jmcdo29** [comment]
Fixed in v 1.1.3. There's now a `getTracker()` method that can be overriden and there's a quick mention in the readme about it. If you'd like to update the docs repo as well, that would be great.
