### ISSUE TITLE
Example for RPC

### ISSUE THREAD

**Issue by thalysonalexr** [nestjs/throttler#535]
Hi, on top of this repository it reads "A rate limiting module for NestJS to work with Fastify, Express, GQL, Websockets, and RPC   ".

Can you give me an example of how to use with RPC?

**Comment by jmcdo29** [comment]
What would you consider the defining factor of how to rate limit a microservice? With GQL, REST, and WS we can use IP address, but most RPC implementations don't keep the caller's IP address because the request gets sent to the message broker and then pushed to the microservice server.

You can override the guard's `handleRequest` method and set up all the deterministic values, but in my opinion the microservice gateway is what should be rate limited, not the microservice itself.
